// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lffastfufqwvspmtpbvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZmFzdGZ1ZnF3dnNwbXRwYnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMzUxMDIsImV4cCI6MjA4NTgxMTEwMn0.gxAzlrCKeXmAGUnW9NKuayv-gSGWylQPgzCRwNx9NDg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);